var spec_files =
{
  'organization' : ['id', 'name', 'alternate_name', 'description', 'email',
                    'url', 'tax_status', 'tax_id', 'year_incorporated'],
  'program' : ['id', 'organization_id', 'name', 'alternate_name'],
  'service' : ['id', 'organization_id', 'program_id', 'location_id', 'name',
               'alternate_name', 'description', 'url', 'email', 'status',
               'application_process', 'wait_time'],
  'location' : ['id', 'organization_id', 'name', 'alternate_name',
                'transportation', 'latitude', 'longitude', 'description'],
  'phone' : ['id', 'service_id', 'organization_id', 'contact_id', 'number',
             'extension', 'type', 'department', 'country_prefix'],
  'contact' : ['id', 'organization_id', 'service_id', 'name', 'title',
               'department', 'email'],
  'physical_address' : ['id', 'location_id', 'attention', 'address_1',
                        'address_2', 'address_3', 'address_4', 'city',
                        'state_province', 'postal_code', 'country'],
  'postal_address' : ['id', 'location_id', 'attention', 'address_1',
                      'address_2', 'address_3', 'address_4', 'city',
                      'state_province', 'postal_code', 'country'],
  'regular_schedule' : ['id', 'service_id', 'location', 'weekday', 'opens_at',
                        'closes_at'],
  'holiday_schedule' : ['id', 'service_id', 'location_id', 'opens_at',
                        'closes_at', 'closed', 'start_date', 'end_date'],
  'metadata' : ['id', 'resource_id', 'last_action_date', 'last_action_type',
                'field_name', 'previous_value', 'replacement_value',
                'updated_by'],
  'accreditation' : ['id', 'organization_id', 'accreditation'],
  'license' : ['id', 'organization_id', 'license'],
  'funding' : ['id', 'organization_id', 'service', 'source'],
  'eligibility' : ['id', 'service_id', 'eligibility'],
  'service_area' : ['id', 'service_id', 'service_area'],
  'required_document' : ['id', 'service_id', 'document'],
  'fee' : ['id', 'service_id', 'fee'],
  'payment_accepted' : ['id', 'service_id', 'payment'],
  'interpretation_services' : ['id', 'service_id', 'language'],
  'language' : ['id', 'service_id', 'location_id', 'language'],
  'accessibility_for_disabilities' : ['id', 'location_id', 'accesibility'],
  'meta_table_description' : ['id', 'name', 'language', 'character_set'],
  'service_at_location' : ['id', 'service_id', 'location_id', 'email', 'url']
}
